In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import StandardScaler # Scaling is suggested when running a gradient descent algorithm

import matplotlib # a plotting library
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
%matplotlib inline

In [2]:
df = pd.read_csv ('games_data.csv')
data = df.to_numpy()
X = data[:100 , [1,2,3,4,5,8,9,10,11,12,13]]
y = data[:100 , 6]

(100, 11)
(100,)


In [3]:
for i in range(X.shape[0]):
    X[i][0] = len(X[i][0])
print(X)

[[18 638.0 2.02 ... 0.0 4.42 11.0]
 [13 1992.0 1.53 ... 0.0 4.04 6.0]
 [19 1364.0 1.01 ... 0.0 0.089 6.0]
 ...
 [28 1395.0 1.09 ... 1.0 1.83 8.0]
 [21 4835.0 2.0 ... 1.0 49.46 4.0]
 [17 594.0 1.89 ... 1.0 8.58 2.0]]


In [5]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[0])

[-0.55201331 -0.69094953  1.09554111 -0.48449975 -0.97692534  0.05712305
  0.08177026 -0.55504491 -1.12815215 -0.27663263  1.26930346]


In [6]:
# Reshape y into a rank 2 matrix y_2d(<np.ndarray>)
y_2d = y.reshape(y.shape[0],1)
print("shape of y_2d: ", y_2d.shape)

shape of y_2d:  (100, 1)


In [7]:
N = X_scaled.shape[0]
print(N)

100


In [8]:
ones = np.ones((N,1),dtype=np.int16) 
X_1 =  np.hstack((ones,X_scaled))
print("shape of X_1: ", X_1.shape)

shape of X_1:  (100, 12)


In [9]:
def compute_cost(X_1, y, w, N):
    # Write your code in place of ellipsis. Cost can be calculated using a single line of code.
    # Remember w is a vector here.
    cost= ((1/(2*N))*((X_1.dot(w)) - y)**2).sum()
    return cost

In [10]:
def gradient_descent(X_1 , y , learning_rate , w , n , num_iters):
    # In place of ellipsis, write the updated value of w0 in temp0 and of w1 in temp1
    # Finish the gradient descent function
    for i in range(num_iters):
        # derivative vector is given by : X_train.Transpose *  (( X_train * w)- y ) 
        # You may add your own variables
        
        wT = w.T
        w = w - (learning_rate/n)*(X_1.T.dot((X_1.dot(w)-y)))
        if (i%100==0):
            # In place of ellipsis, call the cost you just coded above
            cost = compute_cost(X_1,y,w,N)

            # You can uncomment print statements below to see how cost changes, 
            # but please make sure you put prints in comments before submission
            #print("Cost")
            #print(cost)
            
    return w

In [12]:
def multiple_linear_reg_model_gda(X_1 , y , n , learning_rate , num_iters):

    #initialize the values of parameter vector w. It should be a column vector of zeros of dimension(d+1,1)
    w = np.zeros((X_1.shape[1],1))

    #calculate the initial cost by calling the function you coded above.
    initial_cost= compute_cost(X_1,y,w,n)
#     print("Initial Cost")
#     print(initial_cost)

    #calculate the optimized value of gradients by calling the gradient_descent function coded above 
    w = gradient_descent(X_1, y, learning_rate, w, n, num_iters)
    
    # Calculate the cost with the optimized value of w0 and w1 by calling the cost function.    
    final_cost = compute_cost(X_1, y, w, n)
    #print("Final Cost")
    #print(final_cost)
    
    return w, initial_cost, final_cost

In [13]:
learning_rate = .002
num_iters = 100000
results = multiple_linear_reg_model_gda(X_1,y_2d, N, learning_rate, num_iters)

w = results[0]
print("w: ", w, "\ninitial cost: ", results[1], "\nfinal cost: ", results[2])

w:  [[3.2389999999998897]
 [-0.07616791519153317]
 [0.24748112167298617]
 [-0.2853024016066768]
 [-0.06439792749280034]
 [-0.4867019668780324]
 [-0.21328523855021084]
 [0.14024932671859486]
 [0.18402017663966252]
 [0.195369730044554]
 [0.08063554404924937]
 [0.058981504102343374]] 
initial cost:  5.55415 
final cost:  0.15731884403554067


In [14]:
def predict(x, w_opt): 
    ones = np.ones((x.shape[0],1),dtype=np.int16) 
    x_aug =  np.hstack((ones,x))
    
    predicted_y = w_opt.T.dot(x_aug.T)
    
    return predicted_y

In [15]:
y_predict = predict(X_scaled,w)
print(y_predict)
print(y)

[[3.03345797459005 3.5097992982854938 2.3702725968439187
  3.0740246333734826 3.6850234109609086 2.400878780226736
  3.7877719427324665 2.412546438992585 2.9783805228627878
  3.3606213959270517 2.6282767823491446 3.1594210027396086
  2.915022858663201 2.8430519107249874 2.891071374127697
  2.966783260573077 3.178888905670627 2.8469880760288024
  2.705252654179997 2.9563510112039175 3.045822039876519
  2.879961991073873 3.2462175410958154 3.051450199207412
  3.0185007768863454 2.8929290923115656 3.0364150786924826
  2.829141937938161 2.879151820351131 2.846385529195764
  2.8572900522503613 2.828782771125841 2.9192459799602775
  2.8884105069021953 2.4423983603672066 3.6315641526660913
  2.554148768631738 2.3388697200062594 2.914784407421554 2.61546883743038
  3.0359245250081797 3.2443212031075275 3.07930770621998 2.69562691313536
  3.4043974301024567 3.9392257460199267 3.4502080217145146
  3.399667257964667 2.5171319891903727 4.1092531467387765
  3.8788203781953645 2.4882848332696685 3.6

In [16]:
print(y_predict.sum())
print(y.sum())
print(np.mean(y))
RSS = ((y_predict - y)**2).sum()
TSS = ((np.mean(y)- y)**2).sum()
R2 = 1- (RSS / TSS)
print("RSS = {0:f}".format(RSS))
print("TSS = {0:f}".format(TSS))
print("R^2 = {0:f}".format(R2))

323.89999999998895
323.9000000000001
3.2390000000000008
RSS = 31.463769
TSS = 61.717900
R^2 = 0.490200


In [19]:
#Slightly better with standardization

In [20]:
y_val = data[103:123 , 6]
X_val = data[103:123 , [1,2,3,4,5,8,9,10,11,12,13]]
for i in range(X_val.shape[0]):
    X_val[i][0] = len(X_val[i][0])
scaler = StandardScaler()
X_val_scaled = scaler.fit_transform(X_val)  

In [22]:
y_val_predict = predict(X_val_scaled,w)


In [25]:
print(y_val_predict.sum())
print(y_val.sum())
print(np.mean(y_val))
RSS = ((y_val_predict - y_val)**2).sum()
TSS = ((np.mean(y_val)- y_val)**2).sum()
R2 = 1- (RSS / TSS)
print("RSS = {0:f}".format(RSS))
print("TSS = {0:f}".format(TSS))
print("R^2 = {0:f}".format(R2))

64.7799999999978
67.8
3.3899999999999997
RSS = 8.380127
TSS = 14.498000
R^2 = 0.421980


In [40]:
X_1 = data[:100 , [1,2,3,5,8,9,10,11,12]]
for i in range(X_1.shape[0]):
    X_1[i][0] = len(X_1[i][0])
scaler = StandardScaler()
X_d = scaler.fit_transform(X_1)

ones = np.ones((N,1),dtype=np.int16) 
X_1 =  np.hstack((ones,X_d))

learning_rate = .002
num_iters = 100000
results = multiple_linear_reg_model_gda(X_1,y_2d, N, learning_rate, num_iters)

w = results[0]
print("w: ", w, "\ninitial cost: ", results[1], "\nfinal cost: ", results[2])

y_predict = predict(X_d,w)
print(y_predict)

print(y_predict.sum())
print(y.sum())
print(np.mean(y))
RSS = ((y_predict - y)**2).sum()
TSS = ((np.mean(y)- y)**2).sum()
R2 = 1- (RSS / TSS)
print("RSS = {0:f}".format(RSS))
print("TSS = {0:f}".format(TSS))
print("R^2 = {0:f}".format(R2))

w:  [[3.2389999999998897]
 [-0.07307304861111595]
 [0.21185242114791575]
 [-0.24196967039301978]
 [-0.4394744314311822]
 [-0.2675424276760634]
 [0.18721675479501917]
 [0.19950908288422453]
 [0.1981882175492442]
 [0.050538525444159904]] 
initial cost:  5.55415 
final cost:  0.1594579071225721
[[2.9489263047586625 3.4843174352017114 2.3877206666388764
  3.182106604874858 3.608214008751536 2.4240489134392065
  3.8722556171566715 2.385182664970339 3.0246844195534286
  3.257183981940124 2.6380333539538077 3.2488662937723234
  2.9734420363289322 2.860141264874207 2.8422280855955986
  2.9747054154789074 2.933515384800822 2.8023501465428433
  2.697720718692368 2.9804137021100767 3.016750539173507
  2.8815092129517166 3.168721245934077 2.9418656206956646
  2.9919238989340338 2.8922839111403276 2.958666254454919
  2.8613287582791815 2.796905272960812 2.751243634806219
  2.8115344013407277 2.8017806641942378 2.8836658359995027
  2.9503505290323924 2.473782780184662 3.6062715890474197
  2.62026284