In [52]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier




In [53]:
df = pd.read_csv ('games_data.csv')
data = df.to_numpy()
X = data[:100 , [1,2,3,4,5,8,9,10,11,12,13]]
y = data[:100 , 6]

X_val = data[103:123, [1,2,3,4,5,8,9,10,11,12,13]]
y_val = data[103:123, 6]

In [54]:
for i in range(X.shape[0]):
    X[i][0] = len(X[i][0])
print(X)

[[18 638.0 2.02 ... 0.0 4.42 11.0]
 [13 1992.0 1.53 ... 0.0 4.04 6.0]
 [19 1364.0 1.01 ... 0.0 0.089 6.0]
 ...
 [28 1395.0 1.09 ... 1.0 1.83 8.0]
 [21 4835.0 2.0 ... 1.0 49.46 4.0]
 [17 594.0 1.89 ... 1.0 8.58 2.0]]


In [55]:
y_encoded = [] #using Neural Networking, categorize the game to success or not. 
for i in range(y.shape[0]):
    if y[i] >= 2.5:
        y_encoded.append(1)
    else:
        y_encoded.append(0)

In [56]:
scaler = StandardScaler()
X= scaler.fit_transform(X)
print(X[94,:])

[ 2.81836498  0.24996324 -0.49219963 -0.24617965  0.29450384 -0.17136916
 -0.20514293  3.32870892  0.88640526 -0.33323308  0.68838654]


In [57]:
training_model = MLPClassifier(solver='lbfgs', alpha=0.0001, hidden_layer_sizes=(5, 5), random_state=1)

In [58]:
training_model.fit(X, y_encoded)


MLPClassifier(hidden_layer_sizes=(5, 5), random_state=1, solver='lbfgs')

In [59]:
for i in range(X_val.shape[0]):
    X_val[i][0] = len(X_val[i][0])
print(X_val)

[[40 2382.0 1.76 42126.0 17.3 15.0 20.0 19.99 1.0 47.3 6.0]
 [46 1352.0 1.06 29593.0 81.4 8.0 10.0 4.99 0.0 3.9 7.0]
 [24 2999.0 2.27 8141.0 10.5 80.0 100.0 29.99 0.0 7.7 8.0]
 [13 4515.0 2.33 145216.0 2.0 35.0 40.0 39.99 1.0 45.5 3.0]
 [13 3972.0 2.14 133500.0 1.7 50.0 60.0 7.99 1.0 31.6 5.0]
 [13 2985.0 2.29 59841.0 8.5 35.0 40.0 39.99 1.0 34.0 3.0]
 [18 2936.0 2.22 6640.0 12.5 60.0 80.0 9.99 0.0 0.153 8.0]
 [12 1734.0 1.12 900.0 38.2 2.0 3.0 4.99 0.0 1.2 3.0]
 [10 3993.0 2.99 21750.0 5.4 20.0 25.0 29.99 0.0 0.2 7.0]
 [17 2894.0 2.24 84884.0 11.3 20.0 25.0 29.99 1.0 49.0 3.0]
 [10 1395.0 1.03 277.0 90.6 0.0 1.0 7.99 0.0 0.276 5.0]
 [10 287.0 1.01 258.0 98.1 0.0 1.0 1.24 0.0 1.24 7.0]
 [21 2831.0 1.72 37843.0 9.2 15.0 20.0 19.99 0.0 60.33 5.0]
 [20 1345.0 1.02 851.0 93.9 0.0 1.0 0.49 0.0 0.109 3.0]
 [21 1325.0 1.05 2644.0 88.0 0.0 1.0 12.99 0.0 0.665 6.0]
 [14 1399.0 1.06 1583.0 87.6 2.0 3.0 14.99 0.0 1.3 7.0]
 [18 1373.0 1.05 1963.0 86.3 1.0 2.0 15.99 0.0 4.3 3.0]
 [25 2342.0 1.77 82

In [60]:
y_val_encoded = [] #using Neural Networking, categorize the game to success or not. 
for i in range(y_val.shape[0]):
    if y[i] >= 2.5:
        y_val_encoded.append(1)
    else:
        y_val_encoded.append(0)

In [61]:
result = training_model.predict(X_val)

In [62]:
sum = 0
for i in range(X_val.shape[0]):
    if result[i] == y_val_encoded[i]:
        sum += 1
accuracy = sum/X_val.shape[0]
print(accuracy)

0.75
